### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by adamstac** [thechangelog/changelog.com#92]
This is a working checklist of things to do or check at launch:
- [x] Update return URLs from Campaign Monitor for Weekly and Nightly
- [x] Have Dan email Apple to transfer Founders Talk listing to me `adamstac@mac.com`
- [x] Inform Dan of new feed URLs for The Changelog and Founders Talk
- [x] Remove Basic Auth requirement
- [x] Update Twitter background/profile images
- [x] Disable Go Time and RFC SoundCloud downloads
- [x] Set up analytics
- [x] Add to Google Webmaster
